# Generated by Django 6.0.1 on 2026-02-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/detail/'),
        ),
    ]
