# Generated by Django 6.0.1 on 2026-02-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_item_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/detail/', verbose_name='Изображение для карточки (Full-art)'),
        ),
    ]
